### ISSUE TITLE
「氯鎦」等字 建議改用思源黑體TW版本

### ISSUE THREAD

**Issue by Binjohn** [ButTaiwan/genyog-font#9]
最近打了元素週期表，發現源樣黑體的「氯鎦」等元素寫法怪怪的，建議用思源黑體的TW版本取代。

![氯鎦](https://user-images.githubusercontent.com/43265566/55347350-341cec00-54e7-11e9-99c2-4fcaa1039a74.png)

**Comment by CoolMarvel43** [comment]
抱歉，我不可能繼續打中文，因為我的中文不太流利。I cannot be typing in Chinese all the time, as I cannot describe this suggestion properly in that language. Use Google Translate if anyone doesn't understand.

My suggestion: Instead of taking from the TW 台灣標準字形 version, maybe **use a font editor** and **modify** those two glyphs (Extralight and Heavy weights only first, then interpolate the rest of the weights between them), so as to look something like this:

![Screen Shot 2019-07-23 at 22 13 05](https://user-images.githubusercontent.com/10541683/61719219-18d83400-ad97-11e9-91cd-0669b59d401a.png)

I used Adobe Illustrator for this mockup. Take the 彔 and 留 parts from 箓 and 瑠 respectively, as those components have traditional print forms.

That way we can keep the traditional print form without resorting to 台灣標準字形 to make the form look "correct" for Chinese use.

**Comment by ButTaiwan** [comment]
此專案只從思源系列選擇相對好的字符，**絕對**不自己造、改任何一個字符。這是最基本原則。
改下去就沒完沒了了，太多字都會想動手。

這是開源專案，歡迎fork～～～

**Comment by lapomme** [comment]
@Marcus98T 台北黑體的作者會造字，可以向他提議

**Comment by CoolMarvel43** [comment]
> 台北黑體的作者會造字，可以向他提議

我本來想說這個，可惜要給他圖片email attachment不會那麼容易。我也不想開Facebook戶口。

> 此專案只從思源系列選擇相對好的字符，絕對不自己造、改任何一個字符。這是最基本原則。
> 改下去就沒完沒了了，太多字都會想動手。
>
> 這是開源專案，歡迎fork～～～

OK，算了，如果要fork，那源石黑體還是源流明體要怎麼做？在Fontforge使用自動script改風格嗎？

https://github.com/adobe-fonts/source-han-sans/issues/182#issuecomment-434141040

> We actually have over 3K JP glyphs that were never released, because of the architectural limit. Many of these are virtually identical to a Chinese glyph, but many are unique. We can certainly consider providing the masters of those glyphs as part of our long-term plan.

另外，Ken Lunde說過，他們考慮在遙遠未來發佈沒有進入思源黑體的三千JP字型的masters。比如，「氯」字在思源黑體是CN的，但是在思源宋體是JP的。「氯」字可能有JP版的黑體，但是因為技術限制（65535 字型限制），就沒有進入v1.000，所以思源黑體從來沒有JP版的「氯」字。要未發佈JP masters還要等很久咯。

**Comment by ButTaiwan** [comment]
> OK，算了，如果要fork，那源石黑體還是源流明體要怎麼做？在Fontforge使用自動script改風格嗎？

這個也要請自己處理耶。

有考慮未來 release script，不過目前架構太亂，還欠缺整理，這也是個long-term plan....

**Comment by KrasnayaPloshchad** [comment]
如果能提供一些可靠的資料來佐證，比如從一些舊書舊報上拍攝或掃描得來的圖像，興許會更好。

**Comment by ButTaiwan** [comment]
Ver 1.500 這兩個字已改選TW字形。
![image](https://user-images.githubusercontent.com/5418570/79038935-10b77180-7c10-11ea-8943-ec89c675be88.png)

**Comment by aikahiiragi** [comment]
改了後的「鎦」字「金偏旁」的「人」頂……老實說，難看。
原先的「鎦」字雖然「卯」沒縮短撇和豎，但本來看起來還平均的。
